/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FishingTracker;

///import Pollution.MainAppGUI;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Dylan
 */
public class FishermanGUI extends javax.swing.JFrame {

    /**
     * Creates new form FishermanGUI
     */
    
    
    ArrayList<Fisherman> fishermanList;
    
    
    public FishermanGUI() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(173, 216, 230)); // Light blue
        fishermanList = new ArrayList();
        loadFile();
    }

    
    private void loadFile() {
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;
        try{
            f = new File("fishermanList.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);
            ///save the file data to arraylist
            // we need to remind java what type of object we are getting from file
            //cast it to arraylist holding our libraryitem obj
            fishermanList = (ArrayList<Fisherman>)oStream.readObject();
            oStream.close();
        } catch(IOException | ClassNotFoundException e) {
            System.out.println("File input " + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appNameLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        idLBL = new javax.swing.JLabel();
        ageLBL = new javax.swing.JLabel();
        fishingLevelLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        fishingAreaTF = new javax.swing.JTextField();
        startFishingBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        fishingAreaLBL1 = new javax.swing.JLabel();
        fishingLevelTF = new javax.swing.JTextField();
        fishermanIMGLBL = new javax.swing.JLabel();
        mainMenuBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(777, 560));

        appNameLBL.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        appNameLBL.setText("Fisherman Details");

        nameLBL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLBL.setText("Name:");

        idLBL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        idLBL.setText("ID:");

        ageLBL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ageLBL.setText("Age:");

        fishingLevelLBL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fishingLevelLBL.setText("Fishing Level:");

        fishingAreaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishingAreaTFActionPerformed(evt);
            }
        });

        startFishingBTN.setBackground(new java.awt.Color(0, 0, 204));
        startFishingBTN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        startFishingBTN.setForeground(new java.awt.Color(255, 255, 255));
        startFishingBTN.setText("Start Fishing");
        startFishingBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startFishingBTNActionPerformed(evt);
            }
        });

        exitBTN.setBackground(new java.awt.Color(0, 0, 204));
        exitBTN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        exitBTN.setForeground(new java.awt.Color(255, 255, 255));
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        fishingAreaLBL1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fishingAreaLBL1.setText("Fishing Area:");

        fishingLevelTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishingLevelTFActionPerformed(evt);
            }
        });

        fishermanIMGLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FishImages/fisherman.png"))); // NOI18N
        fishermanIMGLBL.setText("jLabel1");

        mainMenuBTN.setBackground(new java.awt.Color(0, 0, 204));
        mainMenuBTN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mainMenuBTN.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBTN.setText("Main Menu");
        mainMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainMenuBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appNameLBL)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(fishermanIMGLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLBL)
                                    .addComponent(idLBL)
                                    .addComponent(ageLBL)
                                    .addComponent(fishingLevelLBL)
                                    .addComponent(fishingAreaLBL1))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fishingAreaTF, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(idTF)
                                    .addComponent(ageTF)
                                    .addComponent(fishingLevelTF)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(startFishingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(appNameLBL)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLBL)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLBL)
                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageLBL)
                            .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(fishingAreaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fishingAreaLBL1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fishingLevelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fishingLevelLBL))
                .addGap(68, 68, 68)
                .addComponent(startFishingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fishermanIMGLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mainMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fishingAreaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishingAreaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fishingAreaTFActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void startFishingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startFishingBTNActionPerformed
        // TODO add your handling code here:
        
        String name = nameTF.getText();
        String id = idTF.getText();
        String ageString = ageTF.getText();
        int age = Integer.parseInt(ageString);
        String fishingArea = fishingAreaTF.getText();
        String fishingLevel = fishingLevelTF.getText();
        Fisherman tempF = new Fisherman(name, id, fishingArea, fishingLevel, age);
        fishermanList.add(tempF);
        //declare file class, fileOutputStream, ObjectOutputStream
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        try {
            f = new File("fishermanList.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            //write arraylist to file 
            oStream.writeObject(fishermanList);
            ///close file
            oStream.close();
            ///textArea.append("Successfully saved file");

        } catch(IOException e) {
            System.out.println("I/O e: " + e);
        }
        for(Fisherman temp:fishermanList) {
            System.out.println(temp.printDetails());
        }
        JOptionPane.showMessageDialog(null, "New Fisherman Added");
        new FishInputGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_startFishingBTNActionPerformed

    private void fishingLevelTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishingLevelTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fishingLevelTFActionPerformed

    private void mainMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBTNActionPerformed
        // TODO add your handling code here:
        ///new MainAppGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainMenuBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FishermanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FishermanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FishermanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FishermanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FishermanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLBL;
    private javax.swing.JTextField ageTF;
    private javax.swing.JLabel appNameLBL;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel fishermanIMGLBL;
    private javax.swing.JLabel fishingAreaLBL1;
    private javax.swing.JTextField fishingAreaTF;
    private javax.swing.JLabel fishingLevelLBL;
    private javax.swing.JTextField fishingLevelTF;
    private javax.swing.JLabel idLBL;
    private javax.swing.JTextField idTF;
    private javax.swing.JButton mainMenuBTN;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton startFishingBTN;
    // End of variables declaration//GEN-END:variables
}
