/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FishingTracker;

///import Pollution.MainAppGUI;
import Pollution.MainAppGUI;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Dylan
 */
public class FishermanGUI extends javax.swing.JFrame {

    /**
     * Creates new form FishermanGUI
     */
    
    
    ArrayList<Fisherman> fishermanList;
    
    
    public FishermanGUI() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(173, 216, 230)); // Light blue
        fishermanList = new ArrayList();
        loadFile();
    }

    
    private void loadFile() {
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;
        try{
            f = new File("fishermanList.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);
            ///save the file data to arraylist
            //cast it to arraylist holding our fisherman obj
            fishermanList = (ArrayList<Fisherman>)oStream.readObject();
            oStream.close();
        } catch(IOException | ClassNotFoundException e) {
            System.out.println("File input " + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appNameLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        idLBL = new javax.swing.JLabel();
        ageLBL = new javax.swing.JLabel();
        fishingLevelLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        fishingAreaTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        fishingAreaLBL1 = new javax.swing.JLabel();
        fishingLevelTF = new javax.swing.JTextField();
        fishermanIMGLBL = new javax.swing.JLabel();
        mainMenuBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        startBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fishermanTA = new javax.swing.JTextArea();
        infoLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(777, 560));

        appNameLBL.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        appNameLBL.setText("Fisherman Details");

        nameLBL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLBL.setText("Name:");

        idLBL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        idLBL.setText("ID:");

        ageLBL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ageLBL.setText("Age:");

        fishingLevelLBL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fishingLevelLBL.setText("Fishing Level:");

        fishingAreaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishingAreaTFActionPerformed(evt);
            }
        });

        addBTN.setBackground(new java.awt.Color(0, 0, 204));
        addBTN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addBTN.setForeground(new java.awt.Color(255, 255, 255));
        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        exitBTN.setBackground(new java.awt.Color(0, 0, 204));
        exitBTN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        exitBTN.setForeground(new java.awt.Color(255, 255, 255));
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        fishingAreaLBL1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fishingAreaLBL1.setText("Fishing Area:");

        fishingLevelTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishingLevelTFActionPerformed(evt);
            }
        });

        fishermanIMGLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FishImages/fisherman.png"))); // NOI18N
        fishermanIMGLBL.setText("jLabel1");

        mainMenuBTN.setBackground(new java.awt.Color(0, 0, 204));
        mainMenuBTN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mainMenuBTN.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBTN.setText("Main Menu");
        mainMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBTNActionPerformed(evt);
            }
        });

        searchBTN.setBackground(new java.awt.Color(0, 0, 204));
        searchBTN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        searchBTN.setForeground(new java.awt.Color(255, 255, 255));
        searchBTN.setText("SEARCH");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        startBTN.setBackground(new java.awt.Color(0, 0, 204));
        startBTN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        startBTN.setForeground(new java.awt.Color(255, 255, 255));
        startBTN.setText("START FISHING");
        startBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBTNActionPerformed(evt);
            }
        });

        fishermanTA.setColumns(20);
        fishermanTA.setRows(5);
        jScrollPane1.setViewportView(fishermanTA);

        infoLBL.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        infoLBL.setText("Enter Your Details Below");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainMenuBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(fishermanIMGLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLBL)
                                    .addComponent(idLBL)
                                    .addComponent(ageLBL)
                                    .addComponent(fishingLevelLBL)
                                    .addComponent(fishingAreaLBL1))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fishingAreaTF, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                        .addComponent(idTF)
                                        .addComponent(ageTF)
                                        .addComponent(fishingLevelTF))
                                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))
                            .addComponent(appNameLBL)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoLBL)
                                .addGap(39, 39, 39)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appNameLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLBL)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(fishermanIMGLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(startBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fishingAreaLBL1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameLBL)
                                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idLBL)
                                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ageLBL)
                                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(fishingAreaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fishingLevelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fishingLevelLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fishingAreaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishingAreaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fishingAreaTFActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        //creating variable to parse after validation
        int age;
        //taking user inputs and storing in strings
        String name = nameTF.getText();
        String fishermanID = idTF.getText();
        String ageString = ageTF.getText();
        String fishingArea = fishingAreaTF.getText();
        String fishingLevel = fishingLevelTF.getText();
        
        //Ensure inputs are filled out and not null
        if (name.isEmpty() || fishermanID.isEmpty() || ageString.isEmpty() || fishingArea.isEmpty() || fishingLevel.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No field can be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ///creating a try catch and parsing age to an int 
        ///validating the parsed input insuring it's a number using NumberFormatException
        try {
             age = Integer.parseInt(ageString);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Age must be a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Fisherman tempF = new Fisherman(name, fishermanID, fishingArea, fishingLevel, age);
        fishermanList.add(tempF);
        //declare file class, fileOutputStream, ObjectOutputStream
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        try {
            f = new File("fishermanList.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            //write arraylist to file 
            oStream.writeObject(fishermanList);
            ///close file
            oStream.close();
           

        } catch(IOException e) {
            System.out.println("I/O e: " + e);
        }
//        for(Fisherman temp:fishermanList) {
//            ///System.out.println(temp.printDetails());
//        }
        fishermanTA.setText("Fisherman Added Successfully");
        
    }//GEN-LAST:event_addBTNActionPerformed

    private void fishingLevelTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishingLevelTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fishingLevelTFActionPerformed

    private void mainMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBTNActionPerformed
        // TODO add your handling code here:
        ///open main menu and close this jframe
        new MainAppGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainMenuBTNActionPerformed

    private void startBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBTNActionPerformed
        // TODO add your handling code here:
        ///open fishInput jframe and close this jframe
        new FishInputGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_startBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
        
        // Search for fishermanID
        String fishermanID = JOptionPane.showInputDialog(this, "Enter Fisherman ID to delete:");

            ///ensuring a value was entered and not null
        if (fishermanID == null) {
            JOptionPane.showMessageDialog(this, "Fisherman ID cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // loop created to find the correct fishermanID 
        String fishermanSearch = "";
        boolean found = false;
        for (Fisherman fisherman : fishermanList) {
            if (fisherman.getFishermanID().equals(fishermanID)) { ///calling the getFishID method from fish
                fishermanSearch += fisherman.printDetails();
                found = true; /// set found to true
                break;
            }
        }
        //display found object from fisherman array
        fishermanTA.setText(fishermanSearch);

        // if fisherman id was not found respond to user and ask to try again 
        if (!found) {
            JOptionPane.showMessageDialog(this, "Fish with ID " + fishermanID + " does not exist, please try again", "Fail", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_searchBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FishermanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FishermanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FishermanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FishermanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FishermanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel ageLBL;
    private javax.swing.JTextField ageTF;
    private javax.swing.JLabel appNameLBL;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel fishermanIMGLBL;
    private javax.swing.JTextArea fishermanTA;
    private javax.swing.JLabel fishingAreaLBL1;
    private javax.swing.JTextField fishingAreaTF;
    private javax.swing.JLabel fishingLevelLBL;
    private javax.swing.JTextField fishingLevelTF;
    private javax.swing.JLabel idLBL;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel infoLBL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenuBTN;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton searchBTN;
    private javax.swing.JButton startBTN;
    // End of variables declaration//GEN-END:variables
}
